# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kaben/Developer/Source/heekscad-kaben/heekscad/heekscnc/libarea

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kaben/Developer/Source/heekscad-kaben/heekscad/heekscnc/libarea

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kaben/Developer/Source/heekscad-kaben/heekscad/heekscnc/libarea/CMakeFiles /home/kaben/Developer/Source/heekscad-kaben/heekscad/heekscnc/libarea/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kaben/Developer/Source/heekscad-kaben/heekscad/heekscnc/libarea/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named area

# Build rule for target.
area: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 area
.PHONY : area

# fast build rule for target.
area/fast:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/build
.PHONY : area/fast

#=============================================================================
# Target rules for targets named heeksarea

# Build rule for target.
heeksarea: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 heeksarea
.PHONY : heeksarea

# fast build rule for target.
heeksarea/fast:
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/build
.PHONY : heeksarea/fast

# target to build an object file
Arc.o:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/Arc.o
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/Arc.o
.PHONY : Arc.o

# target to preprocess a source file
Arc.i:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/Arc.i
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/Arc.i
.PHONY : Arc.i

# target to generate assembly for a file
Arc.s:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/Arc.s
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/Arc.s
.PHONY : Arc.s

# target to build an object file
Area.o:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/Area.o
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/Area.o
.PHONY : Area.o

# target to preprocess a source file
Area.i:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/Area.i
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/Area.i
.PHONY : Area.i

# target to generate assembly for a file
Area.s:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/Area.s
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/Area.s
.PHONY : Area.s

# target to build an object file
AreaBoolean.o:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/AreaBoolean.o
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/AreaBoolean.o
.PHONY : AreaBoolean.o

# target to preprocess a source file
AreaBoolean.i:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/AreaBoolean.i
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/AreaBoolean.i
.PHONY : AreaBoolean.i

# target to generate assembly for a file
AreaBoolean.s:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/AreaBoolean.s
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/AreaBoolean.s
.PHONY : AreaBoolean.s

# target to build an object file
AreaDxf.o:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/AreaDxf.o
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/AreaDxf.o
.PHONY : AreaDxf.o

# target to preprocess a source file
AreaDxf.i:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/AreaDxf.i
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/AreaDxf.i
.PHONY : AreaDxf.i

# target to generate assembly for a file
AreaDxf.s:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/AreaDxf.s
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/AreaDxf.s
.PHONY : AreaDxf.s

# target to build an object file
AreaOrderer.o:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/AreaOrderer.o
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/AreaOrderer.o
.PHONY : AreaOrderer.o

# target to preprocess a source file
AreaOrderer.i:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/AreaOrderer.i
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/AreaOrderer.i
.PHONY : AreaOrderer.i

# target to generate assembly for a file
AreaOrderer.s:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/AreaOrderer.s
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/AreaOrderer.s
.PHONY : AreaOrderer.s

# target to build an object file
AreaPocket.o:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/AreaPocket.o
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/AreaPocket.o
.PHONY : AreaPocket.o

# target to preprocess a source file
AreaPocket.i:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/AreaPocket.i
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/AreaPocket.i
.PHONY : AreaPocket.i

# target to generate assembly for a file
AreaPocket.s:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/AreaPocket.s
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/AreaPocket.s
.PHONY : AreaPocket.s

# target to build an object file
Circle.o:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/Circle.o
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/Circle.o
.PHONY : Circle.o

# target to preprocess a source file
Circle.i:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/Circle.i
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/Circle.i
.PHONY : Circle.i

# target to generate assembly for a file
Circle.s:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/Circle.s
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/Circle.s
.PHONY : Circle.s

# target to build an object file
Curve.o:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/Curve.o
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/Curve.o
.PHONY : Curve.o

# target to preprocess a source file
Curve.i:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/Curve.i
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/Curve.i
.PHONY : Curve.i

# target to generate assembly for a file
Curve.s:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/Curve.s
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/Curve.s
.PHONY : Curve.s

# target to build an object file
PythonStuff.o:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/PythonStuff.o
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/PythonStuff.o
.PHONY : PythonStuff.o

# target to preprocess a source file
PythonStuff.i:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/PythonStuff.i
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/PythonStuff.i
.PHONY : PythonStuff.i

# target to generate assembly for a file
PythonStuff.s:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/PythonStuff.s
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/PythonStuff.s
.PHONY : PythonStuff.s

# target to build an object file
dxf.o:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/dxf.o
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/dxf.o
.PHONY : dxf.o

# target to preprocess a source file
dxf.i:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/dxf.i
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/dxf.i
.PHONY : dxf.i

# target to generate assembly for a file
dxf.s:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/dxf.s
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/dxf.s
.PHONY : dxf.s

# target to build an object file
kbool/src/booleng.o:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/booleng.o
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/booleng.o
.PHONY : kbool/src/booleng.o

# target to preprocess a source file
kbool/src/booleng.i:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/booleng.i
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/booleng.i
.PHONY : kbool/src/booleng.i

# target to generate assembly for a file
kbool/src/booleng.s:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/booleng.s
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/booleng.s
.PHONY : kbool/src/booleng.s

# target to build an object file
kbool/src/graph.o:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/graph.o
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/graph.o
.PHONY : kbool/src/graph.o

# target to preprocess a source file
kbool/src/graph.i:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/graph.i
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/graph.i
.PHONY : kbool/src/graph.i

# target to generate assembly for a file
kbool/src/graph.s:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/graph.s
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/graph.s
.PHONY : kbool/src/graph.s

# target to build an object file
kbool/src/graphlst.o:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/graphlst.o
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/graphlst.o
.PHONY : kbool/src/graphlst.o

# target to preprocess a source file
kbool/src/graphlst.i:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/graphlst.i
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/graphlst.i
.PHONY : kbool/src/graphlst.i

# target to generate assembly for a file
kbool/src/graphlst.s:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/graphlst.s
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/graphlst.s
.PHONY : kbool/src/graphlst.s

# target to build an object file
kbool/src/instonly.o:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/instonly.o
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/instonly.o
.PHONY : kbool/src/instonly.o

# target to preprocess a source file
kbool/src/instonly.i:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/instonly.i
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/instonly.i
.PHONY : kbool/src/instonly.i

# target to generate assembly for a file
kbool/src/instonly.s:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/instonly.s
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/instonly.s
.PHONY : kbool/src/instonly.s

# target to build an object file
kbool/src/line.o:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/line.o
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/line.o
.PHONY : kbool/src/line.o

# target to preprocess a source file
kbool/src/line.i:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/line.i
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/line.i
.PHONY : kbool/src/line.i

# target to generate assembly for a file
kbool/src/line.s:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/line.s
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/line.s
.PHONY : kbool/src/line.s

# target to build an object file
kbool/src/link.o:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/link.o
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/link.o
.PHONY : kbool/src/link.o

# target to preprocess a source file
kbool/src/link.i:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/link.i
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/link.i
.PHONY : kbool/src/link.i

# target to generate assembly for a file
kbool/src/link.s:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/link.s
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/link.s
.PHONY : kbool/src/link.s

# target to build an object file
kbool/src/lpoint.o:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/lpoint.o
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/lpoint.o
.PHONY : kbool/src/lpoint.o

# target to preprocess a source file
kbool/src/lpoint.i:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/lpoint.i
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/lpoint.i
.PHONY : kbool/src/lpoint.i

# target to generate assembly for a file
kbool/src/lpoint.s:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/lpoint.s
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/lpoint.s
.PHONY : kbool/src/lpoint.s

# target to build an object file
kbool/src/node.o:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/node.o
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/node.o
.PHONY : kbool/src/node.o

# target to preprocess a source file
kbool/src/node.i:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/node.i
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/node.i
.PHONY : kbool/src/node.i

# target to generate assembly for a file
kbool/src/node.s:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/node.s
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/node.s
.PHONY : kbool/src/node.s

# target to build an object file
kbool/src/record.o:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/record.o
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/record.o
.PHONY : kbool/src/record.o

# target to preprocess a source file
kbool/src/record.i:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/record.i
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/record.i
.PHONY : kbool/src/record.i

# target to generate assembly for a file
kbool/src/record.s:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/record.s
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/record.s
.PHONY : kbool/src/record.s

# target to build an object file
kbool/src/scanbeam.o:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/scanbeam.o
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/scanbeam.o
.PHONY : kbool/src/scanbeam.o

# target to preprocess a source file
kbool/src/scanbeam.i:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/scanbeam.i
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/scanbeam.i
.PHONY : kbool/src/scanbeam.i

# target to generate assembly for a file
kbool/src/scanbeam.s:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kbool/src/scanbeam.s
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kbool/src/scanbeam.s
.PHONY : kbool/src/scanbeam.s

# target to build an object file
kurve/Construction.o:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kurve/Construction.o
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kurve/Construction.o
.PHONY : kurve/Construction.o

# target to preprocess a source file
kurve/Construction.i:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kurve/Construction.i
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kurve/Construction.i
.PHONY : kurve/Construction.i

# target to generate assembly for a file
kurve/Construction.s:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kurve/Construction.s
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kurve/Construction.s
.PHONY : kurve/Construction.s

# target to build an object file
kurve/Finite.o:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kurve/Finite.o
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kurve/Finite.o
.PHONY : kurve/Finite.o

# target to preprocess a source file
kurve/Finite.i:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kurve/Finite.i
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kurve/Finite.i
.PHONY : kurve/Finite.i

# target to generate assembly for a file
kurve/Finite.s:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kurve/Finite.s
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kurve/Finite.s
.PHONY : kurve/Finite.s

# target to build an object file
kurve/Matrix.o:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kurve/Matrix.o
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kurve/Matrix.o
.PHONY : kurve/Matrix.o

# target to preprocess a source file
kurve/Matrix.i:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kurve/Matrix.i
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kurve/Matrix.i
.PHONY : kurve/Matrix.i

# target to generate assembly for a file
kurve/Matrix.s:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kurve/Matrix.s
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kurve/Matrix.s
.PHONY : kurve/Matrix.s

# target to build an object file
kurve/kurve.o:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kurve/kurve.o
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kurve/kurve.o
.PHONY : kurve/kurve.o

# target to preprocess a source file
kurve/kurve.i:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kurve/kurve.i
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kurve/kurve.i
.PHONY : kurve/kurve.i

# target to generate assembly for a file
kurve/kurve.s:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kurve/kurve.s
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kurve/kurve.s
.PHONY : kurve/kurve.s

# target to build an object file
kurve/offset.o:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kurve/offset.o
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kurve/offset.o
.PHONY : kurve/offset.o

# target to preprocess a source file
kurve/offset.i:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kurve/offset.i
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kurve/offset.i
.PHONY : kurve/offset.i

# target to generate assembly for a file
kurve/offset.s:
	$(MAKE) -f CMakeFiles/area.dir/build.make CMakeFiles/area.dir/kurve/offset.s
	$(MAKE) -f CMakeFiles/heeksarea.dir/build.make CMakeFiles/heeksarea.dir/kurve/offset.s
.PHONY : kurve/offset.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... area"
	@echo "... edit_cache"
	@echo "... heeksarea"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Arc.o"
	@echo "... Arc.i"
	@echo "... Arc.s"
	@echo "... Area.o"
	@echo "... Area.i"
	@echo "... Area.s"
	@echo "... AreaBoolean.o"
	@echo "... AreaBoolean.i"
	@echo "... AreaBoolean.s"
	@echo "... AreaDxf.o"
	@echo "... AreaDxf.i"
	@echo "... AreaDxf.s"
	@echo "... AreaOrderer.o"
	@echo "... AreaOrderer.i"
	@echo "... AreaOrderer.s"
	@echo "... AreaPocket.o"
	@echo "... AreaPocket.i"
	@echo "... AreaPocket.s"
	@echo "... Circle.o"
	@echo "... Circle.i"
	@echo "... Circle.s"
	@echo "... Curve.o"
	@echo "... Curve.i"
	@echo "... Curve.s"
	@echo "... PythonStuff.o"
	@echo "... PythonStuff.i"
	@echo "... PythonStuff.s"
	@echo "... dxf.o"
	@echo "... dxf.i"
	@echo "... dxf.s"
	@echo "... kbool/src/booleng.o"
	@echo "... kbool/src/booleng.i"
	@echo "... kbool/src/booleng.s"
	@echo "... kbool/src/graph.o"
	@echo "... kbool/src/graph.i"
	@echo "... kbool/src/graph.s"
	@echo "... kbool/src/graphlst.o"
	@echo "... kbool/src/graphlst.i"
	@echo "... kbool/src/graphlst.s"
	@echo "... kbool/src/instonly.o"
	@echo "... kbool/src/instonly.i"
	@echo "... kbool/src/instonly.s"
	@echo "... kbool/src/line.o"
	@echo "... kbool/src/line.i"
	@echo "... kbool/src/line.s"
	@echo "... kbool/src/link.o"
	@echo "... kbool/src/link.i"
	@echo "... kbool/src/link.s"
	@echo "... kbool/src/lpoint.o"
	@echo "... kbool/src/lpoint.i"
	@echo "... kbool/src/lpoint.s"
	@echo "... kbool/src/node.o"
	@echo "... kbool/src/node.i"
	@echo "... kbool/src/node.s"
	@echo "... kbool/src/record.o"
	@echo "... kbool/src/record.i"
	@echo "... kbool/src/record.s"
	@echo "... kbool/src/scanbeam.o"
	@echo "... kbool/src/scanbeam.i"
	@echo "... kbool/src/scanbeam.s"
	@echo "... kurve/Construction.o"
	@echo "... kurve/Construction.i"
	@echo "... kurve/Construction.s"
	@echo "... kurve/Finite.o"
	@echo "... kurve/Finite.i"
	@echo "... kurve/Finite.s"
	@echo "... kurve/Matrix.o"
	@echo "... kurve/Matrix.i"
	@echo "... kurve/Matrix.s"
	@echo "... kurve/kurve.o"
	@echo "... kurve/kurve.i"
	@echo "... kurve/kurve.s"
	@echo "... kurve/offset.o"
	@echo "... kurve/offset.i"
	@echo "... kurve/offset.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

